after_success: 
  - "npm run report-coverage"
branches: 
  only: 
    - master
cache: 
  directories: 
    - node_modules
install: 
  - "npm install"
language: node_js
node_js: 
  - "6.3.1"
notifications: 
  email: false
script: 
  - "npm run build"
  - "npm run test"
  - "npm run check-coverage"
sudo: false