sudo:false
language: node_js
cache:
	directories:
		- node_modules
notifications:
	email: false
node_js:
  - "6.3.1"
install:
  - npm install
script:
  - npm run build
  - npm run test
  - npm run check-coverage
after_success:
	- npm run report-coverage