after_success: 
  - "npm run report-coverage"
cache: 
  directories: 
    - node_modules
before_script: 
  - "npm install"
language: node_js
node_js: 
  - iojs
notifications: 
  email: false
script: 
  - "npm run build"
  - "npm run test"
  - "npm run check-coverage"
